apiVersion: v1
kind: PersistentVolume
metadata:
  name: pihole-pv
  labels:
      app: pihole
      directory: etc
  finalizers: 
    - kubernetes.io/pv-protection
spec:
  storageClassName: default
  capacity:
    storage: 750M
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /var/pods/data/pihole/
    type: Directory
  nodeAffinity:   # must set
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{NODE_AFFINITY}}

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pihole-pv2
  labels:
      app: pihole
      directory: dnsmasq
  finalizers: 
    - kubernetes.io/pv-protection
spec:
  storageClassName: default
  capacity:
    storage: 100M
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /var/pods/data/pihole/
    type: Directory
  nodeAffinity:   # must set
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - "{{NODE_AFFINITY}}"