apiVersion: v1
kind: Service
metadata:
  name: pihole-sv
  namespace: default
spec:
  selector:
    app: pihole
  ports:
    - name: webport
      protocol: TCP
      port: 80
      targetPort: 80
    - name: query-tcp
      protocol: TCP
      port: 53
      targetPort: 53
    - name: query-udp
      protocol: UDP
      port: 53
      targetPort: 53
  externalTrafficPolicy: Local
  type: LoadBalancer
  loadBalancerIP: {{IP_PIHOLE}}